<?php
// @codingStandardsIgnoreFile
?>
<!--footer-->
<div class="row">
  <div class="large-12 columns footer">
    <div class="sumome-plugin-center social-media">
      <h4 class="list-number-title">Show Us Love and Give Us a Follow</h4>
      <div>
        <a href="https://twitter.com/SumoMe" target="_blank"><img class="appsumo-twitter" src="<?php print $this->skinURL.'images/twitter.png'?>"></a>
        <a href="https://www.facebook.com/sumo/" target="_blank"><img class="appsumo-facebook" src="<?php print $this->skinURL.'images/facebook.png'?>"></a>
        <a href="https://www.instagram.com/sumome/" target="_blank"><img class="appsumo-instagram" src="<?php print $this->skinURL.'images/instagram.png'?>"></a>
      </div>
    </div>

      <!-- Site ID -->
      <div class="row">
        <div class="large-12 columns footer footer">
          <div class="sumome-plugin-center">Need to restore an existing account?
            <div class="sumome-plugin-linkalike sumome-link-button sumome-tile-advanced-settings item-tile sumome-popup-no-dim" data-name="sumome-control-advanced-settings" data-title="">Click here</div>
          </div>
        </div>
      </div>

  </div>
</div>
